version: '3'

services:
  rippy_playlist1:
    build: .
    container_name: rippy_playlist1
    restart: unless-stopped
    volumes:
      - ./playlists.toml:/app/playlists.toml:ro
      - ./secrets.toml:/app/secrets.toml:ro
      - ./data/playlist1:/data
    environment:
      - PLAYLIST_INDEX=1
    command: /bin/bash -c "
      url=$$(awk '/^\[\[playlists\]\]/ {count++} count==1 && /^url/ {gsub(/.*= *\"?/, \"\"); gsub(/\".*/, \"\"); print; exit}' /app/playlists.toml) &&
      /app/scripts/rippy.sh \"$$url\" /data"

  rippy_playlist2:
    build: .
    container_name: rippy_playlist2
    restart: unless-stopped
    volumes:
      - ./playlists.toml:/app/playlists.toml:ro
      - ./secrets.toml:/app/secrets.toml:ro
      - ./data/playlist2:/data
    environment:
      - PLAYLIST_INDEX=2
    command: /bin/bash -c "
      url=$$(awk '/^\[\[playlists\]\]/ {count++} count==2 && /^url/ {gsub(/.*= *\"?/, \"\"); gsub(/\".*/, \"\"); print; exit}' /app/playlists.toml) &&
      /app/scripts/rippy.sh \"$$url\" /data"

  rippy_playlist3:
    build: .
    container_name: rippy_playlist3
    restart: unless-stopped
    volumes:
      - ./playlists.toml:/app/playlists.toml:ro
      - ./secrets.toml:/app/secrets.toml:ro
      - ./data/playlist3:/data
    environment:
      - PLAYLIST_INDEX=3
    command: /bin/bash -c "
      url=$$(awk '/^\[\[playlists\]\]/ {count++} count==3 && /^url/ {gsub(/.*= *\"?/, \"\"); gsub(/\".*/, \"\"); print; exit}' /app/playlists.toml) &&
      /app/scripts/rippy.sh \"$$url\" /data"